//specificity

export const contentActionType = {

    CATEGORIES_FEATCH: 'CATEGORIES_FEATCH',
    CATEGORIES_DETAILS: 'CATEGORIES_DETAILS',
    ALL_NEWS: 'ALL_NEWS',
    ADD_CONTENT: 'ADD_CONTENT',
    USER_INFO: 'USER_INFO',
    ALL_USER_DATA: 'ALL_USER_DATA',
    MAKE_ADMIN: 'MAKE_ADMIN'
}